### PR TITLE
Renamed to nethserver-ejabberd-next

### PR DESCRIPTION
**Pull request by stephdl**
no ejabberd version required you are free to break your server

### CODE REVIEW

**Comment by Neustradamus** [comment]
@stephdl: Nice :)

Ready to see my improvements in the new version too.

**Comment by stephdl** [comment]
@Neustradamus to be honest I am not sure I will be the main maintener of this rpm, I do it to make a kickstart hence any PR and maintener are welcome

**Comment by Neustradamus** [comment]
I am happy because I see that people wait the new build since a long time in NS, and it permits to change the current NS status.

There are a lot of improvements and bugfixes since the last version included in NS.

Official ejabberd sources and packages are here:
- https://www.process-one.net/en/ejabberd/downloads/
- https://github.com/processone/ejabberd/tags

I think it is not hard to create a 21.12 in NS.

PS: Maybe you can see to integrate Fedora/RedHat packager team (temporary or not) and your work will be excellent to all OS, not only for NS admins/users ^^

**Comment by stephdl** [comment]
obsoleted by https://github.com/NethServer/nethserver-ejabberd-next/pull/1

**Comment by Neustradamus** [comment]
Thanks @stephdl!

Some improvements are in my Issues/PRs, please look it :)
- https://github.com/search?o=desc&p=4&q=org%3ANethServer+author%3ANeustradamus&s=updated&type=Issues

Note: Some PRs have been merged but not in main/master code, and I have removed some improvements in my machine because of inactivity, happy to see status changes after several years.

**Pull request closed without merging**
