### PR TITLE
Update 70C2sS2SConf

### PR DESCRIPTION
**Pull request by Doc-Saintly**
Updating max queue to align with ejabberd suggested default. This value is too low and can cause rapid disconnects when joining large MUCs.

### CODE REVIEW

**Comment by stephdl** [comment]
it seems the default values is `10000`, why we only have 1000 as default
https://docs.ejabberd.im/admin/configuration/listen-options/#max-fsm-queue

It seems it was an old default value but probably increased with the time, in the example of configuration you can find

```
[root@prometheus ~]# grep -srni 'max_fsm_queue' /opt/ejabberd
/opt/ejabberd/conf/ejabberd.yml:146:max_fsm_queue: 10000
```

I tend to think either we move to `10000` or guardedly we make a e-smith db property with the default value of `1000` that you can increase easily with the terminal and following by  an event ?

what do you think @gsanchietti

**Comment by gsanchietti** [comment]
Let's move to the upstream default.

@Doc-Saintly can you raise it to the new default of 10K?

**Comment by Doc-Saintly** [comment]
> Let's move to the upstream default.
> 
> @Doc-Saintly can you raise it to the new default of 10K?

Done :)

**Review by gsanchietti — APPROVED** [review]
Thank you for the change, this is ok for me!
Let's wait @stephdl approval ;)

**Review by stephdl — APPROVED** [review]
A big thank you mate

**Comment by gsanchietti** [comment]
Released:
nethserver-ejabberd-1.8.2-1.ns7.noarch.rpm

**Pull request merged**
