### PR TITLE
Upgrade to 20.03 version

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/6108

### CODE REVIEW

**Comment by stephdl** [comment]
```
2020-04-04 11:34:21.255 [warning] <0.106.0>@ejabberd_config_transformer:warn_removed_option:539 Option 'log_rotate_date' is deprecated and has no effect anymore. Please remove it from the configuration.
2020-04-04 11:34:21.255 [warning] <0.106.0>@ejabberd_config_transformer:warn_removed_option:539 Option 'log_rate_limit' is deprecated and has no effect anymore. Please remove it from the configuration.
```

need to check

**Comment by Neustradamus** [comment]
# Do not cache authentication (introduced by 20.01)
or
 # Do not cache authentication (introduced by 20.03) 

Please look for options...

**Comment by stephdl** [comment]
it should be already done, please valid it

**Comment by Neustradamus** [comment]
@stephdl: I think that you have changed the 20.01 to 20.03 but it must not.
Look my previous message.

**Comment by stephdl** [comment]
we use default value in our configuration file and the log warns these settings are obsolete and can be removed : `log_rotate_date` & `log_rate_limit`

https://github.com/processone/ejabberd/blob/2d32c66fd7e323d456bfe0b06947eec0bfe43d40/src/ejabberd_logger.erl#L151
https://github.com/processone/ejabberd/blob/2d32c66fd7e323d456bfe0b06947eec0bfe43d40/src/ejabberd_logger.erl#L154

the code to warn is at 

https://github.com/processone/ejabberd/blob/2d32c66fd7e323d456bfe0b06947eec0bfe43d40/src/ejabberd_config_transformer.erl#L151
https://github.com/processone/ejabberd/blob/2d32c66fd7e323d456bfe0b06947eec0bfe43d40/src/ejabberd_config_transformer.erl#L154

but the doc states that it is still usable :| 

https://docs.ejabberd.im/admin/guide/troubleshooting/#log-files


I think it is safe to remove them because we use the default values

```
log_rotate_date: ""
log_rate_limit: 100
```

**Comment by Neustradamus** [comment]
No you do not use default configuration!
5223 is not in the default configuration ;)
It must be an option in Nethgui/Cockpit...

Please read here and look links for obsolete parts:
- https://community.nethserver.org/t/ejabberd-improvements-ejabberd-20-03/15062/18?u=neustradamus

**Comment by stephdl** [comment]
@Neustradamus Please do not open discussion here, the community website is there to talk of new features.

**Comment by Neustradamus** [comment]
Have you added "loglevel: info" from the forum link?

And please look configuration of ejabberd.yml.example, no 5523 by default.

**Comment by stephdl** [comment]
> Is it possible to integrate with logrotate instead?

It seems that we need to use some scripts with `postrotate` to `/usr/sbin/ejabberdctl reopen-log` and this could create some issue

**Comment by DavidePrincipi** [comment]
I'd like to integrate with the distro logrotate tool. This simplifies the application of a global log retention policy. This effort is required for third-party applications that are not part of CenOS, like ejabberd.

**Comment by stephdl** [comment]
ok will look

**Comment by stephdl** [comment]
we use now logrotate after the log retention we need to use a script to reopen the log file I had two choices

` /opt/ejabberd-*/bin/ejabberdctl reopen-log > /dev/null 2>&1 || true`
cons: after the log retention, the log is empty and the path will change after each version of ejabberd except if we accept the wild card

`/bin/systemctl reload ejabberd.service > /dev/null 2>/dev/null || true`
I used this one, with the reload it prints 5 lines into the new log, it won't be misleading and the path won't never change

**Comment by gsanchietti** [comment]
> And please look configuration of ejabberd.yml.example, no 5523 by default.

We are going to keep port 5523 for backward compatibility.

**Comment by Neustradamus** [comment]
> We are going to keep port 5523 for backward compatibility.

Yes but you can add in Nethgui/Cockpit an option to disable it (enabled by default of course).
It is the request specified in the forum.

**Comment by Neustradamus** [comment]
Have you seen for "loglevel: info"
- https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L20
- https://docs.ejabberd.im/admin/guide/troubleshooting/

**Comment by stephdl** [comment]
> Have you seen for "loglevel: info"

RTFM please

https://docs.ejabberd.im/admin/guide/troubleshooting/#log-files

**Pull request merged**
