### PR TITLE
Clear cache when the user password is modified locally

### PR DESCRIPTION
**Pull request by stephdl**
https://community.nethserver.org/t/ejabberd-user-password-does-not-work-when-we-change-the-password-in-nethgui-and-cockpit-solution-already-said-several-days-ago/14153/

### CODE REVIEW

**Comment by Neustradamus** [comment]
@stephdl: Any news?

**Comment by stephdl** [comment]
it is waiting your tests :D

**Comment by Neustradamus** [comment]
@stephdl: How really apply?

But you have all my confidence, I think it is good ^^

**Comment by stephdl** [comment]
never trust me, I am always wrong

install the rpm

`yum install http://packages.nethserver.org/nethserver/7.7.1908/autobuild/x86_64/Packages/nethserver-ejabberd-1.5.1-1.2.pr28.g8324dce.ns7.noarch.rpm`

install nethserver-dc or nethserver-directory, create users, change password, check after the change you can login with the new password

**Comment by Neustradamus** [comment]
@stephdl: Can you change the -clearCache filename to -clear-cache?

There is a problem but I think it is about ejabberd directly, the XMPP session of user who has changed the password is not cutted.

**Comment by stephdl** [comment]
> Can you change the -clearCache filename to -clear-cache?

I prefer not, when as a developer

**Comment by Neustradamus** [comment]
@stephdl: It is closed?

All files in the folder have the same base, it is same strategy, it is better to have -clear-cache...

**Comment by Neustradamus** [comment]
- https://github.com/nethserver/nethserver-ejabberd/tree/master/root/etc/e-smith/events/actions
- https://github.com/NethServer/nethserver-base/tree/master/root/etc/e-smith/events/actions
- ...

**Comment by Neustradamus** [comment]
Have you looked for the filename like all others?
- root/etc/e-smith/events/actions/nethserver-ejabberd-clearCache
->  root/etc/e-smith/events/actions/nethserver-ejabberd-clear-cache

For disconnect the user session after the password change, it is needed to do a kick_user user host too!
- https://docs.ejabberd.im/admin/guide/managing/

**Comment by Neustradamus** [comment]
@gsanchietti, @stephdl: Closed? It is solved?

**Comment by gsanchietti** [comment]
StephDL asked to test the new implementation but nobody did it. I saw just comments complaining about the file naming.

We are going to review again the work on next major ejabberd update.

**Pull request closed without merging**
