### PR TITLE
Diffie hellman key for Ejabberd

### PR DESCRIPTION
**Pull request by stephdl**
Enforce encryption by the usage of a diffie hellman key

Following the nomenclature name of ejabberd : https://www.process-one.net/blog/securing-ejabberd-with-tls-encryption/

cc @Neustradamus

### CODE REVIEW

**Comment by stephdl** [comment]
hum testing ejabberd with and without my patch I can see that we still use a DH key before I patch it but I see nothing in the configuration file

before my patch
```
 Testing robust forward secrecy (FS) -- omitting Null Authentication/Encryption, 3DES, RC4 

 FS is offered (OK)           ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256
                              ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 
 Elliptic curves offered:     prime256v1 
 DH group offered:            RFC5114/2048-bit DSA group with 256-bit prime order subgroup (2048 bits)
```


after my patch 
```
 Testing robust forward secrecy (FS) -- omitting Null Authentication/Encryption, 3DES, RC4 

 FS is offered (OK)           ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-SHA256
                              ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 DHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-SHA256 
 Elliptic curves offered:     prime256v1 
 DH group offered:            Unknown DH group (2048 bits)
```

I would like to understand why ?

**Comment by gsanchietti** [comment]
I'm a little lost here.

What this PR is trying to fix?

**Comment by Neustradamus** [comment]
@DavidePrincipi: It is not new, for security, XMPP servers must have a Diffie-Hellman key exchange.
- https://docs.ejabberd.im/admin/configuration/listen-options/#dhfile
- https://www.process-one.net/blog/securing-ejabberd-with-tls-encryption/
- https://prosody.im/doc/advanced_ssl_config#dhparam
- ...

It is missing in NethServer ejabberd configuration file, I have already specified here and on the forum normally:
- https://github.com/NethServer/nethserver-mail/pull/203#issuecomment-650508233

**Comment by Neustradamus** [comment]
@DavidePrincipi: It is not new, for security, XMPP servers must have a Diffie-Hellman key exchange.
- ejabberd docs: https://docs.ejabberd.im/admin/configuration/listen-options/#dhfile
- P1 ejabberd blog: https://www.process-one.net/blog/securing-ejabberd-with-tls-encryption/
- Prosody IM: https://prosody.im/doc/advanced_ssl_config#dhparam
- Tigase XMPP Server: https://docs.tigase.net/tigase-server/8.1.0/Administration_Guide/html_chunk/tlsFeaturesConfiguration.html
- ...

It is missing in NethServer ejabberd configuration file, I have already specified here and on the forum normally:
- https://github.com/NethServer/nethserver-mail/pull/203#issuecomment-650508233

XMPP C2S (Client to Server) and S2S (Server to Server) tests:
- https://xmpp.net/

@stephdl: Thanks for your progress about ejabberd and security in NethServer.

**Comment by Neustradamus** [comment]
@stephdl: Can you change the macro order to have:
```
'CERTFILE': ...
'DHFILE': ...
'TLSOPTS': ...
'CIPHERS': ...
```

**Comment by DavidePrincipi** [comment]
> what is the directive who set to use the DH parameter

    DH group offered:            RFC5114/2048-bit DSA group with 256-bit prime order subgroup (2048 bits)

I guess if a custom file is not specified the RFC group is used instead. It is hard-coded. It is a well-known standard DH group.

I might be wrong because I'm not expert here, but generating a random one should provide some degree of extra security (e.g. https://weakdh.org/). I guess it's the purpose of this PR! 

This is the line of output you get with a custom DH group file:

     DH group offered:            Unknown DH group (2048 bits)

It's "unknown", because it is random IMO.

We should deepen why this PR is required though. For instance for dovecot we didn't generate a random DH group. I guess we are still using the RFC one. For slapd and postfix we implemented the generation... :man_shrugging:

**Comment by stephdl** [comment]
>  For slapd and postfix we implemented the generation... 

For postfix we generated it one because it was 1024, slapd it was simply missing.

**Comment by stephdl** [comment]
Ejabberd use the default DH group of 2048 bit, we have no interest here to use another DH group, for now let's close it

**Comment by Neustradamus** [comment]
Have you added dhfile in configuration file?

**Comment by stephdl** [comment]
see nmap output at https://github.com/NethServer/nethserver-ejabberd/pull/40#issuecomment-771058334

**Pull request closed without merging**
