### PR TITLE
Fix LdapTlsPortOverride db prop name

### PR DESCRIPTION
**Pull request by DavidePrincipi**
The default prop name is wrong

NethServer/dev#6399

### CODE REVIEW

**Comment by DavidePrincipi** [comment]
The file was not named correctly here

https://github.com/NethServer/nethserver-ejabberd/pull/37/files#diff-1459e346fc4101c483327253b7ed9fef3a229a4274cb2cf3baa68bfc61846501

**Review by gsanchietti — APPROVED** [review]
For sure the fix is necessary, but it doesn't change current behavior.

I'm wondering if nobody will ever use such prop.
Maybe it could be easier to remove it completely.

**Comment by DavidePrincipi** [comment]
The purpose is changing the behavior of the ejabberd LDAP client starting from NS 7.10. The prop is required to not alter pre-7.10 installations.

We can drop the prop completely if `starttls` support comes from upstream meanwhile.

**Review by stephdl — APPROVED** [review]

**Comment by gsanchietti** [comment]
Please, go ahead with the merge

**Pull request merged**
