### PR TITLE
Update to 20.03

### PR DESCRIPTION
**Pull request by stephdl**
https://community.nethserver.org/t/ejabberd-improvements-ejabberd-20-03/15062

### CODE REVIEW

**Comment by gsanchietti** [comment]
See https://community.nethserver.org/t/ejabberd-improvements-ejabberd-20-03/15062/7

**Comment by gsanchietti** [comment]
Since there is no real interest on this, I'd like to close the PR and discard changes.

What do you think @stephdl ?

**Comment by stephdl** [comment]
I am a bit upset about @Neustradamus I think !

**Comment by Neustradamus** [comment]
It is a nice update, what is the problem?

I will see for add more options in Cockpit in the future...

**Comment by stephdl** [comment]
obsoleted by https://github.com/NethServer/nethserver-ejabberd/pull/33

**Pull request closed without merging**
